version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_db
      - REDIS_URL=redis://redis:6379
      - BASE_URL=http://localhost:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge